// Action types
export const FETCH_EXCHANGE_ITEMS_PENDING = 'FETCH_EXCHANGE_ITEMS_PENDING';
export const FETCH_EXCHANGE_ITEMS_SUCCESS = 'FETCH_EXCHANGE_ITEMS_SUCCESS';
export const FETCH_EXCHANGE_ITEMS_FAILURE = 'FETCH_EXCHANGE_ITEMS_FAILURE';
export const API_REQUEST = 'API_REQUEST';